version: "2.0"
services:
  mfe-host:
    build:
      context: ./host
    ports:
      - "3000:3000"
    container_name: mfe-host
    stdin_open: true
    depends_on: 
      - mfe-nav
  mfe-nav:
    build:
      context: ./nav
    ports:
      - "3001:3001"
    container_name: mfe-nav
    stdin_open: true
    depends_on: 
      - mfe-store  
  mfe-store:
    build:
      context: ./store
    ports:
      - "80:3002"
    container_name: mfe-store
    stdin_open: true