version: "2.0"
services:
  mfe-host:
    build:
      context: ./host
    ports:
      - "3000:3000"
    container_name: mfe-host
    stdin_open: true
    depends_on: 
      - mfe-nav
    networks:
      - app-network
  mfe-nav:
    build:
      context: ./nav
    ports:
      - "3001:3001"
    container_name: mfe-nav
    stdin_open: true
    depends_on: 
      - mfe-store
    networks:
      - app-network   
  mfe-store:
    build:
      context: ./store
    ports:
      - "3002:3002"
    container_name: mfe-store
    stdin_open: true
    networks:
      - app-network  
